### ISSUE TITLE
Custom properties don't appear in spawned cards

### ISSUE THREAD

**Issue by SwedeRacer** [tjakubo2/Decker#14]
Hello!

Firstly, this library is so useful! I don't know how anyone could implement a complex card game without it.

Now, my issue: I'm trying to add custom properties to cards by including them in the commonParams table parameter of the Decker.Card function. I can see that these properties are part of the json of the cards, either individually or as part of a deck, until the object is spawned. I'm unable to access these properties in my code, and if I spawn some cards and then save my game, the json object representing the cards don't include the properties either. It's as if TTS' spawn function strips out any unrecognized properties (I've also tried using the spawnJSON method).

Thanks,

Shawn

**Comment by tjakubo** [comment]
> It's as if TTS' spawn function strips out any unrecognized properties (I've also tried using the spawnJSON method).

Yup, TTS doesn't let us add arbitrary properties to objects. If you want to add "custom data" to objects, you have to choose an existing property, write to it (using an already spawned object like `obj.script_state = 'hello'` will also save you manually escaping strings etc), and then read and deserialize it when needed.

I've included the `commonParams` table just so people can figure out any new field they know TTS uses and supports, and write to that without needing maintain a complete list of properties in Decker library. But it won't help with what you need, you gotta wrestle TTS on its own grounds when it comes to persisting data.

Also thank you for the kind words, I'm very happy you found it useful :)

**Comment by SwedeRacer** [comment]
Ah, I see. It's weird and frustrating that TTS doesn't make this easier.

Anyway, thanks for the quick reply!
